### ISSUE TITLE
Core assets

### ISSUE THREAD

**Issue by joshgillies** [joshgillies/zion-assets#1]
Identify core assets as helpers.
- [x] [Site](https://github.com/joshgillies/zion-assets/tree/master/assets/site)
- [x] [Folder](https://github.com/joshgillies/zion-assets/tree/master/assets/folder)
- [ ] Standard Page (Ref: #2)
- [ ] Custom Form (Ref: #3)
- [ ] Metadata Schema (Ref: #4)
- [ ] Asset Listing (Ref: #5)

And others...
